spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/department_db
  application:
    name: department_service
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
